# Generated by Django 5.2.8 on 2026-03-01 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='edge',
            name='next_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='come_in', to='network.node'),
        ),
        migrations.AddField(
            model_name='edge',
            name='prev_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='start_from', to='network.node'),
        ),
        migrations.AddField(
            model_name='node',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
