# Generated by Django 5.2.8 on 2026-03-16 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_edge_next_node_edge_prev_node_node_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edge',
            name='next_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming', to='network.node'),
        ),
        migrations.AlterField(
            model_name='edge',
            name='prev_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing', to='network.node'),
        ),
    ]
