# Generated by Django 5.2.8 on 2026-03-19 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_wallet_balance_transaction'),
        ('rides', '0003_offer_dropoff_order_offer_pickup_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rides.trip'),
        ),
    ]
