# Generated by Django 5.2.8 on 2026-03-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_carpoolrequest_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='dropoff_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='offer',
            name='pickup_order',
            field=models.IntegerField(default=0),
        ),
    ]
