# Generated by Django 5.2.8 on 2026-06-13 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_offer_dropoff_order_offer_pickup_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpoolrequest',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='rides.trip'),
        ),
    ]
